steps:
# Pull the existing image
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/$REPO_NAME:latest || exit 0
# Build a docker image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME', '.' ]
# Push the docker image to container registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME"]
images:
 - 'gcr.io/$PROJECT_ID/$REPO_NAME/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'
